### ISSUE TITLE
有没有好的办法兼容4.0+

### ISSUE THREAD

**Issue by l123456789jy** [hujiaweibujidao/FabDialogMorph#1]

**Comment by l123456789jy** [comment]
ActivityOptionsCompat options = ActivityOptionsCompat.makeSceneTransitionAnimation(MainActivity.this, fab, getString(R.string.transition_dialog));
                ActivityCompat.startActivity(MainActivity.this, intent, options.toBundle());

这样只能防止5.0以下不崩溃，5.0以上有效果。

**Comment by xuyisheng** [comment]
过渡动画本身就是5+才有的，没办法兼容5-。android的兼容库已经兼容了很多新特性了，但是这个View相关的，总不能在兼容库中把新的View类都放进去

**Comment by yanbin92** [comment]
哦

**Comment by wuchangfeng** [comment]
请问一下 点击 Dialog 之外的地方是，不能退出 Dialog 对话框 回到全局吗？
