### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by wuchangfeng** [hujiaweibujidao/FabDialogMorph#2]
请问一下 点击 Dialog 之外的地方是，不能退出 Dialog 对话框 回到全局吗？

**Comment by hujiaweibujidao** [comment]
这个问题你可以自己监听这个事件然后处理。

**Comment by wuchangfeng** [comment]
@hujiaweibujidao 嗯 我试着我自己解决了。另外,我才用了第二种方式，但是点击 Dialog 会覆盖顶部导航栏和背后相关的背景。我不知道是哪个地方我少写了还是哪里没考虑到？

**Comment by hujiaweibujidao** [comment]
嗯？你看下你的DialogActivity的布局文件，另外，你看下Manifest文件，我给它加了`android:theme="@style/AppTheme.Dialog"`

**Comment by wuchangfeng** [comment]
ok了,确实是后面没有 指定 AppTheme.Dialog。谢谢啦。
